# -*- coding: utf-8 -*-
"""ข้อมูลกลาง Virtual Lab ทุกชุด จัดตามบทเรียน สสวท. — ใช้ generate virtual-lab.html และ library.html
   (แก้ที่นี่ที่เดียว แล้วรัน python3 _admin/build_virtual_lab.py)"""
V1='Virtual Physics Lab 01/Mechacnics/'; V2='Virtual Physics Lab 02/'; V3='Virtual Physics Lab 03/'
TOPICS=[  # id, icon, ชื่อไทย, English, สี, ระดับหลัก
 ('measure','📏','การวัดและความคลาดเคลื่อน','Measurement & Uncertainty','accent5'),
 ('kinematics','🏃','การเคลื่อนที่แนวตรง','Linear Motion & Kinematics','accent3'),
 ('force','🍎','แรงและกฎการเคลื่อนที่ของนิวตัน',"Forces & Newton's Laws",'accent'),
 ('equilibrium','⚖️','สมดุลกลและโมเมนต์','Equilibrium & Torque','accent'),
 ('projectile','🎯','โพรเจกไทล์และการเคลื่อนที่แบบวงกลม','Projectile & Circular Motion','accent4'),
 ('energy','⚡','งานและพลังงาน','Work & Energy','accent5'),
 ('shm','🌀','การเคลื่อนที่แบบฮาร์มอนิกอย่างง่าย','Simple Harmonic Motion','accent2'),
 ('waves','〰️','คลื่นกล','Mechanical Waves','accent2'),
 ('sound','🔊','เสียง','Sound','accent3'),
 ('light','✨','แสงและทัศนศาสตร์','Light & Optics','accent5'),
 ('electro','🎈','ไฟฟ้าสถิต','Electrostatics','accent4'),
 ('astro','🌌','ดาราศาสตร์และจักรวาลวิทยา','Astronomy & Cosmology','accent4'),
]
GROUPS=[ # กลุ่มใหญ่สำหรับเมนูทางลัด
 ('mech','🔬','กลศาสตร์',['measure','kinematics','force','equilibrium','projectile','energy','shm']),
 ('wave','🌊','คลื่น · เสียง · แสง',['waves','sound','light']),
 ('elec','🔌','ไฟฟ้าและแม่เหล็ก',['electro']),
 ('astro','🌌','ดาราศาสตร์',['astro']),
]
# (access, href, num, title_th, desc, topic, level, series, tags)
LABS=[
 ('vlab:vpl01:lab-1',  V1+'1. measuring_precision.html','1','การวัดอย่างละเอียด (Measuring Precision)','ฝึกวัดด้วยเวอร์เนียร์และไมโครมิเตอร์ อ่านค่าอย่างแม่นยำ','measure','ม.4','vpl01',['การวัด']),
 ('vlab:vpl02:lab-42', V2+'42. measurement-vernier-micrometer.html','42','การวัดด้วยเวอร์เนียร์ & ไมโครมิเตอร์ v2','ฝึกอ่านสเกล Manual/Auto · บันทึกหลายครั้ง · ค่าเฉลี่ยและ σ','measure','ม.4','vpl02',['การวัด','Manual mode']),
 ('vlab:vpl03:lab-1',  V3+'1. precision-measurement-3d.html','L1','การวัดอย่างละเอียด 3D — วงแหวนโลหะ (D · d · h · t)','3D ลากเครื่องมือวัดจริง ชนกันไม่ทะลุ · เลือกความละเอียด 0.05/0.02 mm · ตรวจขีดศูนย์ · x̄ ± Δx̄','measure','ม.4','vpl03',['3D','วงแหวนโลหะ']),
 ('vlab:vpl01:lab-6.1',V1+'6.1 pendulum_timer.html','6.1','นาฬิกาลูกตุ้ม (Pendulum Timer)','วัดเวลาด้วยการแกว่งของลูกตุ้ม','kinematics','ม.4','vpl01',['การวัดเวลา']),
 ('vlab:vpl01:lab-6.2',V1+'6.2water-clock-simulation.html','6.2','นาฬิกาน้ำ (Water Clock)','วัดเวลาด้วยอัตราการไหลคงที่','kinematics','ม.4','vpl01',['การวัดเวลา']),
 ('vlab:vpl01:lab-6.3',V1+'6.3 tape_timer_simulation.html','6.3','เครื่องเคาะสัญญาณเวลา (Tape Timer)','วิเคราะห์การเคลื่อนที่จากจุดบนแถบกระดาษ','kinematics','ม.4','vpl01',['การวัดเวลา']),
 ('vlab:vpl01:lab-7',  V1+'7. strobe_photography_simulation.html','7','ภาพถ่ายสโตรโบสโคป (Strobe Photography)','วิเคราะห์การเคลื่อนที่เป็นช่วง ๆ จากภาพถ่าย','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-8',  V1+'8. straight-line-motion-simulation.html','8','การเคลื่อนที่แนวตรง (Straight Line Motion)','กราฟ s-t, v-t, a-t แบบ real-time','kinematics','ม.4','vpl01',['Kinematics','กราฟ']),
 ('vlab:vpl01:lab-9',  V1+'9. galileo-water-clock-simulation.html','9',"นาฬิกาน้ำของกาลิเลโอ (Galileo's Water Clock)",'พิสูจน์กฎการตกของวัตถุตามกาลิเลโอ','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-11', V1+'11. air_track_simulation.html','11','รางลม (Air Track)','การเคลื่อนที่ไร้แรงเสียดทาน ทดสอบกฎข้อ 1 ของนิวตัน','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-13', V1+'13. free-fall-experiment.html','13','การตกอิสระ (Free Fall)','วัดค่า g ด้วยสโตรโบสโคป','kinematics','ม.4','vpl01',['Free fall','วัด g']),
 ('vlab:vpl01:lab-20', V1+'20. tilted_air_track.html','20','รางลมเอียง (Tilted Air Track)','ความเร่งบนพื้นเอียงไร้แรงเสียดทาน','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-2',  V1+'2. vector_forces_sim.html','2','การรวมเวกเตอร์ของแรง (Vector Addition)','รวมเวกเตอร์แรงแบบกราฟิก พร้อม resultant real-time','force','ม.4','vpl01',['Vector']),
 ('vlab:vpl01:lab-4',  V1+'4. force_resolution_sim.html','4','การแยกองค์ประกอบของแรง (Force Resolution)','แยกแรงในแกน x-y แบบ interactive','force','ม.4','vpl01',['Vector']),
 ('vlab:vpl01:lab-5',  V1+'5. incline_forces.html','5','แรงบนพื้นเอียง (Forces on Incline)','แรงตั้งฉาก แรงเสียดทาน และแรงลงเขา','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-14', V1+'14.mass_weight_simulation.html','14','มวลและน้ำหนัก (Mass vs Weight)','เปรียบเทียบบนดาวต่าง ๆ พร้อมค่า g','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-15', V1+'15. newtons_second_law_simulation.html','15',"กฎข้อ 2 ของนิวตัน (Newton's Second Law)",'F = ma — ปรับแรงและมวล สังเกตความเร่ง','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-18', V1+'18. newton_third_law_simulation.html','18',"กฎข้อ 3 ของนิวตัน (Newton's Third Law)",'แรงกิริยา-ปฏิกิริยา ทุกแรงมีคู่แรงตรงข้ามเท่ากัน','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-3',  V1+'3. torques_simulation.html','3','ทอร์กและสมดุล (Torques)','ระบบคานและแรงหมุน สมดุลต่อการหมุน','equilibrium','ม.4','vpl01',['Torque']),
 ('vlab:vpl01:lab-16', V1+'16. trajectories_simulation.html','16','วิถีโพรเจกไทล์ (Trajectories)','ปรับมุมและความเร็วต้น เปรียบเทียบระยะ','projectile','ม.4','vpl01',['Projectile']),
 ('vlab:vpl01:lab-10', V1+'10. spinning_disc_sim.html','10','จานหมุน (Spinning Disc)','ความเร็วเชิงมุมและโมเมนต์ความเฉื่อย','projectile','ม.4','vpl01',['Circular']),
 ('vlab:vpl01:lab-12', V1+'12. turntable_gravity_simulation.html','12','แรงโน้มถ่วงบนจานหมุน (Turntable Gravity)','แรงเหวี่ยงและแรงสู่ศูนย์กลาง','projectile','ม.4','vpl01',['Circular']),
 ('vlab:vpl01:lab-17', V1+'17. centripetal_force_simulation.html','17','แรงสู่ศูนย์กลาง (Centripetal Force)','F = mv²/r ปรับรัศมีและความเร็ว','projectile','ม.4','vpl01',['Circular']),
    ('vlab:vpl02:lab-62', V2+'62. centripetal-force-whirling-stopper.html','62','แรงสู่ศูนย์กลาง: แกว่งจุกยางผ่านหลอดแก้ว (3D)','แกว่งจุกยางเป็นวงกลม ตุ้มถ่วงให้แรง F = Mg · รักษาคลิปใต้หลอด · จับเวลา N รอบหาคาบ · เปลี่ยน L และ M · กราฟ F กับ 4π²L/T² ความชัน = m · หามวลจุกยางปริศนา','projectile','ม.4','vpl02',['Circular','Centripetal','3D']),
    ('vlab:vpl02:lab-63', V2+'63. conical-pendulum.html','63','ลูกตุ้มกรวย (Conical Pendulum) (3D)','ผลักลูกตุ้มให้วิ่งทับวงกลมอ้างอิง (เบาไป/แรงไปเป็นวงรี) · จับเวลา N รอบ · T = 2π√(h/g) · กราฟ T² กับ h หา g · มวลไม่มีผล · ดาวปริศนา','projectile','ม.4','vpl02',['Circular','Conical pendulum','3D']),
    ('vlab:vpl02:lab-64', V2+'64. banked-curve.html','64','รถเข้าโค้งบนถนนเอียง (Banked Curve) (3D)','สนามทดสอบวงกลมปรับมุมเอียง/รัศมี · เครื่องวัดแรงด้านข้างที่ยาง · หาความเร็วที่ f = 0 ตรวจ tan θ = v²/Rg · เร่งจนยางไถลหา μ · ผิวแห้ง เปียก น้ำแข็ง ปริศนา','projectile','ม.4','vpl02',['Circular','Banked curve','Friction','3D']),
    ('vlab:vpl02:lab-65', V2+'65. vertical-loop.html','65','วงกลมแนวดิ่ง: รางวงรอบ Loop-the-Loop (3D)','ปล่อยรถเข็น/ลูกเหล็กกลิ้งจากความสูง h ลงรางวงรอบรัศมี R · ผ่าน/หลุดจากราง/ไถลกลับ · เซนเซอร์แรงจุดบน-ล่าง + ประตูแสง · หา h_min = 2.5R, 2.7R · กราฟ N_บน กับ h · วัตถุปริศนาหา k','projectile','ม.4','vpl02',['Circular','Vertical circle','Energy','3D']),
    ('vlab:vpl02:lab-66', V2+'66. turntable-friction.html','66','วัตถุบนแผ่นหมุน: แรงเสียดทานเป็นแรงสู่ศูนย์กลาง (3D)','วางเหรียญ ยางลบ ก้อนไม้ วัตถุปริศนาบนแผ่นหมุนที่มีไม้บรรทัด · เร่งรอบช้า ๆ จนวัตถุเริ่มไถล · μₛ = ω²r/g · กราฟ ω² กับ 1/r · วาง 3 ชิ้นดูชิ้นนอกไถลก่อน · ไถลแล้วเคลื่อนเป็นเส้นโค้งตกจากแผ่น','projectile','ม.4','vpl02',['Circular','Friction','3D']),
    ('vlab:vpl02:lab-67', V2+'67. angular-linear-speed-gears.html','67','อัตราเร็วเชิงมุมกับเชิงเส้น: แกนร่วม สายพาน เฟือง จักรยาน (3D)','ประตูแสงวัดคาบของแต่ละล้อ · เครื่องวัดความเร็วผิวที่ขอบ · ตรวจ v = ωr · แกนร่วม ω เท่ากัน · สายพาน/เฟือง v เท่ากัน ω_A r_A = ω_B r_B · หารัศมีล้อปริศนา · ความเร็วจักรยานจากเฟือง','projectile','ม.4','vpl02',['Circular','Angular speed','Gears','3D']),
    ('vlab:vpl02:lab-68', V2+'68. circular-motion-vectors-strobe.html','68','เวกเตอร์ความเร็วและความเร่งในวงกลม: ภาพแฟลชบนโต๊ะลม (3D)','ลูกยางบนโต๊ะลมหมุนด้วยแขนหมุน · ถ่ายภาพแฟลช · สร้าง v₁ v₂ Δv จากภาพ · a = Δv/Δt ชี้เข้าศูนย์กลาง = v²/r · เซนเซอร์แรง F/m · เร่งรอบ a เอียงไปข้างหน้า · ปลดลูกยางแล้วเคลื่อนที่ตามแนวสัมผัส','projectile','ม.4','vpl02',['Circular','Vectors','Strobe','3D']),
    ('vlab:vpl02:lab-69', V2+'69. satellite-orbits-kepler.html','69','ดาวเทียมโคจร: ความเร็ววงโคจรและกฎของเคปเลอร์ (3D)','ปล่อยดาวเทียมที่ความสูง h ด้วยความเร็วแนวระดับ · เรดาร์ความสูงต่ำสุด-สูงสุด หาความเร็ววงกลม v = √(GM/r) · วัดคาบ · กราฟ T² กับ r³ หามวลโลก · ดาวเทียมค้างฟ้า · ดาวเคราะห์ปริศนา · ตก/วงรี/หลุดพ้น','projectile','ม.4','vpl02',['Circular','Satellite','Kepler','3D']),
 ('vlab:vpl01:lab-19', V1+'19.pendulum_energy_sim.html','19','พลังงานของลูกตุ้ม (Pendulum Energy)','พลังงานจลน์-ศักย์ และการอนุรักษ์พลังงาน','energy','ม.4','vpl01',['Energy']),
    ('vlab:vpl02:lab-70', V2+'70. work-force-distance.html','70','งานกับแรงและระยะทาง: ลากกล่องด้วยเครื่องชั่งสปริง (3D)','ชั่งกล่อง · ลากด้วยความเร็วคงตัวที่มุมต่าง ๆ อ่านแรงและระยะ · W = Fs cos θ · งานยกกล่อง mgh · หา μk ของโต๊ะปริศนา','energy','ม.4','vpl02',['Work', 'Force', 'Friction', '3D']),
    ('vlab:vpl02:lab-71', V2+'71. spring-constant-work.html','71','ค่าคงตัวสปริงและงานในการยืดสปริง (3D)','แขวนมวลทีละก้อน อ่านตำแหน่งเข็มบนไม้บรรทัด · กราฟ F–x หา k · งาน = พื้นที่ใต้กราฟ = ½kx² · หามวลก้อนปริศนา · ขีดจำกัดสภาพยืดหยุ่น','energy','ม.4','vpl02',['Hooke', 'Spring', 'Work', '3D']),
    ('vlab:vpl02:lab-72', V2+'72. work-kinetic-energy.html','72','ทฤษฎีบททางาน–พลังงานจลน์: รางลมและโฟโตเกต (3D)','ลากโฟโตเกต 2 ตัวบนราง อ่านตำแหน่งจากสเกล · อ่านเวลาบังลำแสงหาความเร็ว v = การ์ด/เวลา · เทียบ ΔEk กับ W = Mg·s · กราฟ Mg−Ma กับ a หามวลรถและแรงเสียดทานปริศนา','energy','ม.4','vpl02',['Work', 'Energy', 'Air track', '3D']),
    ('vlab:vpl02:lab-73', V2+'73. energy-conservation-ramp.html','73','การอนุรักษ์พลังงานกล: ลูกกลมกลิ้งลงรางโค้ง (3D)','ลากลูกกลมขึ้นรางโค้ง อ่านความสูง h จากสเกล mm · จับเวลาบังโฟโตเกตหา v · กราฟ v²–h · ลูกตัน/ลูกกลวง/แผ่นเลื่อน เห็นพลังงานที่ไปเป็นการหมุน · หา g ของดาวปริศนา','energy','ม.4','vpl02',['Energy', 'Conservation', 'Rolling', '3D']),
    ('vlab:vpl02:lab-74', V2+'74. spring-launcher-projectile.html','74','พลังงานศักย์ยืดหยุ่นยิงวัตถุ: ปืนสปริงบนขอบโต๊ะ (3D)','ลากลูกสูบอัดสปริง อ่าน x บนสเกลกระบอก · อ่านความสูงโต๊ะ H · ยิงแล้ววัดระยะตก R บนสเกลพื้น · กราฟ v²–x² ความชัน = k/m หาค่า k ปริศนา · โจทย์ทำนายระยะตกก่อนยิงจริง','energy','ม.4','vpl02',['Energy', 'Spring', 'Projectile', '3D']),
    ('vlab:vpl02:lab-75', V2+'75. friction-work-stopping-distance.html','75','งานของแรงเสียดทาน: ระยะไถลจนหยุด (3D)','ผลักบล็อกด้วยตัวผลักความเร็วคงที่ · วัด v จากเวลาบังโฟโตเกต · อ่านตำแหน่งหยุดบนสเกล mm · กราฟ v²–s ความชัน = 2μkg · เปลี่ยนมวลแล้วระยะไถลเท่าเดิมไหม · ผิวปริศนา','energy','ม.4','vpl02',['Friction', 'Energy', '3D']),
    ('vlab:vpl02:lab-76', V2+'76. motor-power-efficiency.html','76','กำลังและประสิทธิภาพของมอเตอร์ยกของ (3D)','มอเตอร์ยกตุ้มน้ำหนัก · อ่านความสูงจากสเกล mm จับเวลาด้วยนาฬิกาในฉาก · อ่านโวลต์มิเตอร์และแอมมิเตอร์ · P_out = mgh/t เทียบ P_in = VI · กราฟ η กับโหลด หาโหลดที่ประสิทธิภาพสูงสุด และกระแสขณะไม่มีโหลดปริศนา','energy','ม.4','vpl02',['Power', 'Efficiency', 'Motor', '3D']),
    ('vlab:vpl02:lab-77', V2+'77. simple-machines-incline-pulley.html','77','เครื่องกลอย่างง่าย: พื้นเอียงและรอก (3D)','ลากตาชั่งสปริงด้วยความเร็วคงตัว อ่านแรงพยายาม ระยะที่ดึง และความสูงที่ยกได้ · หา MA, VR และประสิทธิภาพ · เทียบพื้นเอียง รอกตรึง รอกเคลื่อนที่ รอกพวง · หา μk ของพื้นเอียง และมวลก้อนปริศนา','energy','ม.4','vpl02',['Machines', 'Pulley', 'Incline', '3D']),
    ('vlab:vpl02:lab-78', V2+'78. drop-hammer-pile-driver.html','78','ตุ้มตกกระแทกตอกหมุด: พลังงานกลกับแรงต้าน (3D)','ลากตุ้มขึ้นรางน้ำ อ่านความสูง h บนสเกล mm · ปล่อยให้ตกกระแทกหัวหมุด · อ่านความลึกที่หมุดจมบนสเกลข้างหมุด · mgh = F·d · กราฟ d–h หาแรงต้านเฉลี่ยของถาดปริศนา · โจทย์ทำนายก่อนตอก','energy','ม.4','vpl02',['Energy', 'Impact', '3D']),
 ('vlab:vpl01:lab-21', V1+'21. SHM_Linear_Air_Track.html','21','SHM บนรางลม (SHM — Linear Air Track)','การสั่นของมวลติดสปริงบนรางลม','shm','ม.5','vpl01',['SHM']),
 ('vlab:vpl01:lab-42', V1+'42. shm-spring-builder.html','42','SHM03 Spring Builder','ประกอบสปริงเอง อนุกรม/ขนาน · ดิ่ง/ระดับ · กราฟ x, v, a · โหมดสุ่ม k','shm','ม.5','vpl01',['SHM']),
 ('vlab:vpl01:lab-43', V1+'43. shm-phase-explorer.html','43','SHM04 Phase Explorer','Phasor + projection · เฟส 90° ของ y, v, a · กราฟพลังงาน · แดมป์','shm','ม.5','vpl01',['SHM','เฟส']),
 ('vlab:vpl01:lab-44', V1+'44. shm-damping-resonance.html','44','SHM06 Damping & Resonance','Caliper วัดคาบ · Blind mode หา resonance · 6 case จริง (Tacoma · LIGO …)','shm','ม.5','vpl01',['SHM','Resonance']),
 ('vlab:vpl02:lab-30', V2+'30. waves-on-coiled-spring.html','30','คลื่นบนสปริงขด','คลื่นตามยาว/ตามขวาง อัตราเร็ว ความยาวคลื่น','waves','ม.5','vpl02',['Waves']),
 ('vlab:vpl02:lab-31', V2+'31. waves-in-ripple-tank.html','31','ถังคลื่น (Ripple Tank)','หน้าคลื่น ความถี่ ความยาวคลื่นบนผิวน้ำ','waves','ม.5','vpl02',['Waves']),
 ('vlab:vpl02:lab-32', V2+'32. wave-reflection.html','32','การสะท้อนคลื่น','มุมตกกระทบ = มุมสะท้อน ในถังคลื่น','waves','ม.5','vpl02',['Reflection']),
 ('vlab:vpl02:lab-32c',V2+'32C. microwave-reflection.html','32C','การสะท้อนคลื่นไมโครเวฟ','คลื่นแม่เหล็กไฟฟ้าสะท้อนจากแผ่นโลหะ','waves','ม.5','vpl02',['Reflection','EM']),
 ('vlab:vpl02:lab-33', V2+'33. wave-refraction-ripple-tank.html','33','การหักเหคลื่นน้ำ','น้ำลึก-ตื้น อัตราเร็วและความยาวคลื่นเปลี่ยน','waves','ม.5','vpl02',['Refraction']),
 ('vlab:vpl02:lab-37', V2+'37. standing-waves.html','37','คลื่นนิ่งบนเส้นเชือก','บัพ ปฏิบัพ ฮาร์มอนิก','waves','ม.5','vpl02',['Standing wave']),
 ('vlab:vpl02:lab-38', V2+'38. wave-speed-on-string.html','38','ความเร็วคลื่นในเส้นเชือก','v = √(T/μ) ปรับความตึงและมวลต่อความยาว','waves','ม.5','vpl02',['Waves']),
 ('vlab:vpl02:lab-39', V2+'39. phase-circle-wave.html','39','เฟส · วงกลมอ้างอิง · y-x','Virtual Lab 3-in-1 · กราฟ y-t · วิเคราะห์ Δφ','waves','ม.5','vpl02',['เฟส']),
 ('vlab:vpl02:lab-40', V2+'40. pulse-superposition.html','40','การซ้อนทับของคลื่นดล','หลักการซ้อนทับ เสริม/หักล้าง','waves','ม.5','vpl02',['Superposition']),
 ('vlab:vpl02:lab-41', V2+'41. wave-interference-two-source.html','41','การแทรกสอดของคลื่นผิวน้ำ','แหล่งกำเนิดอาพันธ์ 2 แหล่ง แนวบัพ-ปฏิบัพ','waves','ม.5','vpl02',['Interference']),
 ('vlab:vpl02:lab-44', V2+'44. standing-waves-air-column.html','44','คลื่นนิ่งของเสียงในหลอดอากาศ','หลอดปลายปิด/เปิด หาความถี่กำทอนและอัตราเร็วเสียง','sound','ม.5','vpl02',['Sound','Resonance']),
     ('vlab:vpl02:lab-32b',V2+'32B. light-reflection.html','32B','การสะท้อนของแสง (3D)','กระจกเงาราบ 3 มิติสะท้อนภาพจริง · ปักหมุดเล็งภาพในกระจก · กฎการสะท้อน θi = θr · พารัลแลกซ์','light','ม.5','vpl02',['Optics','Reflection','3D']),
     ('vlab:vpl02:lab-33b',V2+'33B. light-refraction-glass.html','33B','การหักเหของแสงผ่านแท่งแก้ว (3D)','ปักหมุดมองผ่านแท่งแก้ว 3 มิติ (หักเหจริง) · กฎของสเนลล์ · วัดมุมด้วยโปรแทรกเตอร์ · ดรรชนีหักเห 8 ตัวกลาง','light','ม.5','vpl02',['Refraction','3D']),
 ('vlab:vpl02:lab-34', V2+'34. wave-diffraction-interference.html','34','การเลี้ยวเบนและแทรกสอด','ช่องเดี่ยว ช่องคู่ แถบสว่าง-มืด','light','ม.5','vpl02',['Diffraction','Interference']),
 ('vlab:vpl02:lab-35', V2+'35. images-converging-lenses.html','35','ภาพจากเลนส์นูน (3D)','ม้านั่งเชิงแสง 3 มิติ · หาโฟกัสด้วยแสงขนาน · ภาพจริง/เสมือน · วัดค่าเอง · สมการเลนส์บาง','light','ม.5','vpl02',['Lens','3D']),
     ('vlab:vpl02:lab-36', V2+'36. images-diverging-lenses.html','36','ภาพจากเลนส์เว้า & กล้องกาลิเลโอ (3D)','ม้านั่งเชิงแสง 3 มิติ · หา f ด้วยลำแสงเลเซอร์ (กราฟ D vs X) · ประกอบกล้องโทรทรรศน์กาลิเลโอ M = −F₁/F₂','light','ม.5','vpl02',['Lens','Telescope','3D']),
 ('vlab:vpl02:lab-46', V2+'46. images-concave-mirror.html','46','ภาพจากกระจกเว้า (3D)','ม้านั่งเชิงแสง 3 มิติ · หาโฟกัสด้วยแสงขนาน · ภาพจริง/เสมือน · วัดค่าเอง · f = R/2','light','ม.5','vpl02',['Mirror','3D']),
    ('vlab:vpl02:lab-47', V2+'47. image-location-parallax-mirrors.html','47','หาตำแหน่งภาพด้วยวิธีพาราแลกซ์ (3D)','กระจกราบ · เว้า · นูน สะท้อนแสงจริง (ray tracing) · ส่ายสายตาตรวจพาราแลกซ์ · ปลายชนปลาย · 1/f = 1/u + 1/v','light','ม.5','vpl02',['Mirror','Parallax','3D']),
    ('vlab:vpl02:lab-48', V2+'48. real-apparent-depth.html','48','ความลึกจริงและความลึกปรากฏ (3D)','ของเหลวในถังแก้ว 3 มิติหักเหแสงจริง (ray tracing) · หาความลึกปรากฏด้วยวิธีไม่มีพาราแลกซ์ · n = ลึกจริง/ลึกปรากฏ · ของเหลวปริศนา','light','ม.5','vpl02',['Refraction','Parallax','3D']),
    ('vlab:vpl02:lab-49', V2+'49. critical-angle-total-internal-reflection.html','49','มุมวิกฤตและการสะท้อนกลับหมด (3D)','แท่งแก้วครึ่งวงกลม 3 มิติหักเหแสงจริง · กฎของสเนลล์ · หามุมวิกฤต n = 1/sin θc · ความสว่างตามสมการเฟรเนล · วัสดุปริศนา','light','ม.5','vpl02',['Refraction','Critical angle','3D']),
    ('vlab:vpl02:lab-50', V2+'50. polarization-malus-law.html','50','โพลาไรเซชันของแสง · กฎของมาลุส (3D)','แผ่นโพลารอยด์ 3 มิติ เห็นเวกเตอร์สนามไฟฟ้าสั่น · วัดทั้ง E และ I · E = E₀ cos θ · I = I₀ cos² θ · แผ่นกลาง 3 แผ่น','light','ม.5','vpl02',['Polarization','Malus','3D']),
    ('vlab:vpl02:lab-51', V2+'51. prism-minimum-deviation-dispersion.html','51','ปริซึม: มุมเบี่ยงเบนน้อยที่สุดและการกระจายแสง (3D)','ปริซึมแก้ว 3 มิติหักเหแสงจริง · หมุนแท่นหา δmin · n = sin((A+δmin)/2)/sin(A/2) · เลเซอร์ 3 สี + แสงขาวแยกเป็นสเปกตรัม','light','ม.5','vpl02',['Prism','Dispersion','3D']),
    ('vlab:vpl02:lab-52', V2+'52. rainbow-primary-secondary.html','52','รุ้งปฐมภูมิและทุติยภูมิในห้องทดลอง (3D)','ทรงกระบอกใสบรรจุน้ำ · เลเซอร์หามุมรุ้ง θ–b (42° / 51°) · แสงขาวลำกว้างเกิดแถบรุ้งจริงบนกระดาษ (ติดตามรังสีหลายพันเส้น) · ลำดับสีกลับกัน','light','ม.5','vpl02',['Rainbow','Dispersion','3D']),
    ('vlab:vpl02:lab-53', V2+'53. double-slit-diffraction-grating.html','53','การแทรกสอดของแสง: สลิตคู่และเกรตติง (3D)','ลวดลายบนฉากคำนวณจากการแทรกสอด+เลี้ยวเบนจริง · วัดระยะแถบด้วยสเกลบนฉาก หาความยาวคลื่น · สลิตเดี่ยว/คู่/เกรตติง · เลเซอร์ปริศนา','light','ม.5','vpl02',['Interference','Diffraction','3D']),
    ('vlab:vpl02:lab-54', V2+'54. electroscope-charging-induction.html','54','อิเล็กโทรสโคปและการทำให้วัตถุมีประจุ (3D)','ถูแท่ง PVC/แก้วกับผ้า · การเหนี่ยวนำ การสัมผัส การต่อลงดิน · อ่านมุมกางแผ่นโลหะ θ–d · ทดสอบชนิดประจุแท่งปริศนา','electro','ม.5','vpl02',['Electrostatics','Induction','3D']),
    ('vlab:vpl02:lab-55', V2+'55. coulombs-law-balance.html','55','กฎของคูลอมบ์ด้วยเครื่องชั่ง (3D)','ทรงกลมตัวนำ 2 ลูก · แหล่งจ่ายไฟแรงสูง · เครื่องชั่ง 0.1 mg · F–1/r² และ F–q₁q₂ (แบ่งประจุ) · หาค่า k · ผลคลาดที่ระยะใกล้','electro','ม.5','vpl02',['Coulomb','Electrostatics','3D']),
    ('vlab:vpl02:lab-56', V2+'56. electric-field-lines-plates.html','56','สนามไฟฟ้า: เส้นสนามในน้ำมัน และแผ่นขนาน (3D)','ผงเซโมลินาเรียงตามสนามจากขั้ว 6 แบบ (คำนวณจากตัวนำจริง) · ทำนาย-สังเกตลวดลาย · กรงฟาราเดย์ · ลูกบอลมีประจุระหว่างแผ่นขนาน tan θ–V/d · E = V/d','electro','ม.5','vpl02',['Electric field','Field lines','3D']),
    ('vlab:vpl02:lab-57', V2+'57. equipotential-mapping.html','57','เส้นศักย์เท่ากันบนกระดาษนำไฟฟ้า (3D)','กระดาษคาร์บอน + ขั้วเงิน 6 แบบ · โวลต์มิเตอร์หาจุดศักย์เท่ากัน ทำเครื่องหมาย เชื่อมเส้น · ตรวจความแม่น · เส้นสนามตั้งฉาก · V–x ระหว่างแท่งขนาน E = ΔV/Δx','electro','ม.5','vpl02',['Equipotential','Potential','3D']),
    ('vlab:vpl02:lab-58', V2+'58. parallel-plate-capacitor.html','58','ตัวเก็บประจุแผ่นขนาน (3D)','แผ่นวงกลมบนราง ปรับ d · อัดประจุ/แยกวงจร/คายผ่านคูลอมบ์มิเตอร์ · C = Q/V · กราฟ C–1/d หา ε₀ · ประจุคงที่ V–d · ฉนวนอะคริลิก/แก้ว/ปริศนา หา κ','electro','ม.5','vpl02',['Capacitor','ε₀','3D']),
    ('vlab:vpl02:lab-59', V2+'59. rc-charge-discharge.html','59','การอัดและคายประจุตัวเก็บประจุ RC (3D)','วงจรจริงบนแผ่นต่อวงจร · ตัวต้านทานแถบสี ±5% · ตัวเก็บประจุ ±20% และตัวปริศนา X · โวลต์มิเตอร์ ไมโครแอมมิเตอร์ นาฬิกาจับเวลา/บันทึกอัตโนมัติ · ln V–t หา τ = RC และ C','electro','ม.5','vpl02',['RC circuit','Capacitor','3D']),
    ('vlab:vpl02:lab-60', V2+'60. millikan-oil-drop.html','60','การทดลองหยดน้ำมันของมิลลิแกน (3D)','พ่นละอองระหว่างแผ่นขนาน · ภาพกล้องจุลทรรศน์มีสเกล การเคลื่อนที่แบบบราวน์ · จับเวลาตก (สโตกส์ + คันนิงแฮม) · ปรับแรงดันลอยนิ่ง q = mgd/V · ฉายรังสีเปลี่ยนประจุ · หาค่า e','electro','ม.6','vpl02',['Millikan','Charge quantization','3D']),
    ('vlab:vpl02:lab-61', V2+'61. capacitor-combinations.html','61','การต่อตัวเก็บประจุแบบอนุกรม ขนาน และผสม (3D)','ต่อ 8 แบบบนแผ่นต่อวงจร · วัดความจุทีละตัวและ C สมมูลด้วยมิเตอร์ · อัดประจุ วัดแรงดันคร่อมแต่ละตัว Q = CV · พลังงาน · การแบ่งประจุและพลังงานที่หายไป','electro','ม.5','vpl02',['Capacitor','Series/Parallel','3D']),
 ('vlab:vpl02:lab-43', V2+'43. big-bang-theory.html','43','ทฤษฎีบิกแบง (Big Bang Theory)','Hubble · BBN · CMB · Build Lab','astro','ม.6','vpl02',['Cosmology']),
 ('vlab:vpl02:lab-45', V2+'45. expanding-universe-balloon.html','45','แบบจำลองการขยายตัวของเอกภพ','ลูกโป่ง = เอกภพ · วัดระยะ-ความเร็ว · กราฟ Hubble v = H·d (กิจกรรม 1.2)','astro','ม.6','vpl02',['Cosmology','Hubble']),
]
SERIES={'vpl01':('VPL 01','Virtual Physics Lab 01'),'vpl02':('VPL 02','Virtual Physics Lab 02'),'vpl03':('VPL 03','Virtual Physics Lab 03 · ปฏิบัติการ ม.')}
