# -*- coding: utf-8 -*-
"""ข้อมูลกลาง Virtual Lab ทุกชุด จัดตามบทเรียน สสวท. — ใช้ generate virtual-lab.html และ library.html
   (แก้ที่นี่ที่เดียว แล้วรัน python3 _admin/build_virtual_lab.py)"""
V1='Virtual Physics Lab 01/Mechacnics/'; V2='Virtual Physics Lab 02/'; V3='Virtual Physics Lab 03/'
TOPICS=[  # id, icon, ชื่อไทย, English, สี, ระดับหลัก
 ('measure','📏','การวัดและความคลาดเคลื่อน','Measurement & Uncertainty','accent5'),
 ('kinematics','🏃','การเคลื่อนที่แนวตรง','Linear Motion & Kinematics','accent3'),
 ('force','🍎','แรงและกฎการเคลื่อนที่ของนิวตัน',"Forces & Newton's Laws",'accent'),
 ('equilibrium','⚖️','สมดุลกลและโมเมนต์','Equilibrium & Torque','accent'),
 ('projectile','🎯','โพรเจกไทล์และการเคลื่อนที่แบบวงกลม','Projectile & Circular Motion','accent4'),
 ('energy','⚡','งานและพลังงาน','Work & Energy','accent5'),
 ('shm','🌀','การเคลื่อนที่แบบฮาร์มอนิกอย่างง่าย','Simple Harmonic Motion','accent2'),
 ('waves','〰️','คลื่นกล','Mechanical Waves','accent2'),
 ('sound','🔊','เสียง','Sound','accent3'),
 ('light','✨','แสงและทัศนศาสตร์','Light & Optics','accent5'),
 ('astro','🌌','ดาราศาสตร์และจักรวาลวิทยา','Astronomy & Cosmology','accent4'),
]
GROUPS=[ # กลุ่มใหญ่สำหรับเมนูทางลัด
 ('mech','🔬','กลศาสตร์',['measure','kinematics','force','equilibrium','projectile','energy','shm']),
 ('wave','🌊','คลื่น · เสียง · แสง',['waves','sound','light']),
 ('astro','🌌','ดาราศาสตร์',['astro']),
]
# (access, href, num, title_th, desc, topic, level, series, tags)
LABS=[
 ('vlab:vpl01:lab-1',  V1+'1. measuring_precision.html','1','การวัดอย่างละเอียด (Measuring Precision)','ฝึกวัดด้วยเวอร์เนียร์และไมโครมิเตอร์ อ่านค่าอย่างแม่นยำ','measure','ม.4','vpl01',['การวัด']),
 ('vlab:vpl02:lab-42', V2+'42. measurement-vernier-micrometer.html','42','การวัดด้วยเวอร์เนียร์ & ไมโครมิเตอร์ v2','ฝึกอ่านสเกล Manual/Auto · บันทึกหลายครั้ง · ค่าเฉลี่ยและ σ','measure','ม.4','vpl02',['การวัด','Manual mode']),
 ('vlab:vpl03:lab-1',  V3+'1. precision-measurement-3d.html','L1','การวัดอย่างละเอียด 3D — วงแหวนโลหะ (D · d · h · t)','3D ลากเครื่องมือวัดจริง ชนกันไม่ทะลุ · เลือกความละเอียด 0.05/0.02 mm · ตรวจขีดศูนย์ · x̄ ± Δx̄','measure','ม.4','vpl03',['3D','วงแหวนโลหะ']),
 ('vlab:vpl01:lab-6.1',V1+'6.1 pendulum_timer.html','6.1','นาฬิกาลูกตุ้ม (Pendulum Timer)','วัดเวลาด้วยการแกว่งของลูกตุ้ม','kinematics','ม.4','vpl01',['การวัดเวลา']),
 ('vlab:vpl01:lab-6.2',V1+'6.2water-clock-simulation.html','6.2','นาฬิกาน้ำ (Water Clock)','วัดเวลาด้วยอัตราการไหลคงที่','kinematics','ม.4','vpl01',['การวัดเวลา']),
 ('vlab:vpl01:lab-6.3',V1+'6.3 tape_timer_simulation.html','6.3','เครื่องเคาะสัญญาณเวลา (Tape Timer)','วิเคราะห์การเคลื่อนที่จากจุดบนแถบกระดาษ','kinematics','ม.4','vpl01',['การวัดเวลา']),
 ('vlab:vpl01:lab-7',  V1+'7. strobe_photography_simulation.html','7','ภาพถ่ายสโตรโบสโคป (Strobe Photography)','วิเคราะห์การเคลื่อนที่เป็นช่วง ๆ จากภาพถ่าย','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-8',  V1+'8. straight-line-motion-simulation.html','8','การเคลื่อนที่แนวตรง (Straight Line Motion)','กราฟ s-t, v-t, a-t แบบ real-time','kinematics','ม.4','vpl01',['Kinematics','กราฟ']),
 ('vlab:vpl01:lab-9',  V1+'9. galileo-water-clock-simulation.html','9',"นาฬิกาน้ำของกาลิเลโอ (Galileo's Water Clock)",'พิสูจน์กฎการตกของวัตถุตามกาลิเลโอ','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-11', V1+'11. air_track_simulation.html','11','รางลม (Air Track)','การเคลื่อนที่ไร้แรงเสียดทาน ทดสอบกฎข้อ 1 ของนิวตัน','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-13', V1+'13. free-fall-experiment.html','13','การตกอิสระ (Free Fall)','วัดค่า g ด้วยสโตรโบสโคป','kinematics','ม.4','vpl01',['Free fall','วัด g']),
 ('vlab:vpl01:lab-20', V1+'20. tilted_air_track.html','20','รางลมเอียง (Tilted Air Track)','ความเร่งบนพื้นเอียงไร้แรงเสียดทาน','kinematics','ม.4','vpl01',['Kinematics']),
 ('vlab:vpl01:lab-2',  V1+'2. vector_forces_sim.html','2','การรวมเวกเตอร์ของแรง (Vector Addition)','รวมเวกเตอร์แรงแบบกราฟิก พร้อม resultant real-time','force','ม.4','vpl01',['Vector']),
 ('vlab:vpl01:lab-4',  V1+'4. force_resolution_sim.html','4','การแยกองค์ประกอบของแรง (Force Resolution)','แยกแรงในแกน x-y แบบ interactive','force','ม.4','vpl01',['Vector']),
 ('vlab:vpl01:lab-5',  V1+'5. incline_forces.html','5','แรงบนพื้นเอียง (Forces on Incline)','แรงตั้งฉาก แรงเสียดทาน และแรงลงเขา','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-14', V1+'14.mass_weight_simulation.html','14','มวลและน้ำหนัก (Mass vs Weight)','เปรียบเทียบบนดาวต่าง ๆ พร้อมค่า g','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-15', V1+'15. newtons_second_law_simulation.html','15',"กฎข้อ 2 ของนิวตัน (Newton's Second Law)",'F = ma — ปรับแรงและมวล สังเกตความเร่ง','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-18', V1+'18. newton_third_law_simulation.html','18',"กฎข้อ 3 ของนิวตัน (Newton's Third Law)",'แรงกิริยา-ปฏิกิริยา ทุกแรงมีคู่แรงตรงข้ามเท่ากัน','force','ม.4','vpl01',['Newton']),
 ('vlab:vpl01:lab-3',  V1+'3. torques_simulation.html','3','ทอร์กและสมดุล (Torques)','ระบบคานและแรงหมุน สมดุลต่อการหมุน','equilibrium','ม.4','vpl01',['Torque']),
 ('vlab:vpl01:lab-16', V1+'16. trajectories_simulation.html','16','วิถีโพรเจกไทล์ (Trajectories)','ปรับมุมและความเร็วต้น เปรียบเทียบระยะ','projectile','ม.4','vpl01',['Projectile']),
 ('vlab:vpl01:lab-10', V1+'10. spinning_disc_sim.html','10','จานหมุน (Spinning Disc)','ความเร็วเชิงมุมและโมเมนต์ความเฉื่อย','projectile','ม.4','vpl01',['Circular']),
 ('vlab:vpl01:lab-12', V1+'12. turntable_gravity_simulation.html','12','แรงโน้มถ่วงบนจานหมุน (Turntable Gravity)','แรงเหวี่ยงและแรงสู่ศูนย์กลาง','projectile','ม.4','vpl01',['Circular']),
 ('vlab:vpl01:lab-17', V1+'17. centripetal_force_simulation.html','17','แรงสู่ศูนย์กลาง (Centripetal Force)','F = mv²/r ปรับรัศมีและความเร็ว','projectile','ม.4','vpl01',['Circular']),
 ('vlab:vpl01:lab-19', V1+'19.pendulum_energy_sim.html','19','พลังงานของลูกตุ้ม (Pendulum Energy)','พลังงานจลน์-ศักย์ และการอนุรักษ์พลังงาน','energy','ม.4','vpl01',['Energy']),
 ('vlab:vpl01:lab-21', V1+'21. SHM_Linear_Air_Track.html','21','SHM บนรางลม (SHM — Linear Air Track)','การสั่นของมวลติดสปริงบนรางลม','shm','ม.5','vpl01',['SHM']),
 ('vlab:vpl01:lab-42', V1+'42. shm-spring-builder.html','42','SHM03 Spring Builder','ประกอบสปริงเอง อนุกรม/ขนาน · ดิ่ง/ระดับ · กราฟ x, v, a · โหมดสุ่ม k','shm','ม.5','vpl01',['SHM']),
 ('vlab:vpl01:lab-43', V1+'43. shm-phase-explorer.html','43','SHM04 Phase Explorer','Phasor + projection · เฟส 90° ของ y, v, a · กราฟพลังงาน · แดมป์','shm','ม.5','vpl01',['SHM','เฟส']),
 ('vlab:vpl01:lab-44', V1+'44. shm-damping-resonance.html','44','SHM06 Damping & Resonance','Caliper วัดคาบ · Blind mode หา resonance · 6 case จริง (Tacoma · LIGO …)','shm','ม.5','vpl01',['SHM','Resonance']),
 ('vlab:vpl02:lab-30', V2+'30. waves-on-coiled-spring.html','30','คลื่นบนสปริงขด','คลื่นตามยาว/ตามขวาง อัตราเร็ว ความยาวคลื่น','waves','ม.5','vpl02',['Waves']),
 ('vlab:vpl02:lab-31', V2+'31. waves-in-ripple-tank.html','31','ถังคลื่น (Ripple Tank)','หน้าคลื่น ความถี่ ความยาวคลื่นบนผิวน้ำ','waves','ม.5','vpl02',['Waves']),
 ('vlab:vpl02:lab-32', V2+'32. wave-reflection.html','32','การสะท้อนคลื่น','มุมตกกระทบ = มุมสะท้อน ในถังคลื่น','waves','ม.5','vpl02',['Reflection']),
 ('vlab:vpl02:lab-32c',V2+'32C. microwave-reflection.html','32C','การสะท้อนคลื่นไมโครเวฟ','คลื่นแม่เหล็กไฟฟ้าสะท้อนจากแผ่นโลหะ','waves','ม.5','vpl02',['Reflection','EM']),
 ('vlab:vpl02:lab-33', V2+'33. wave-refraction-ripple-tank.html','33','การหักเหคลื่นน้ำ','น้ำลึก-ตื้น อัตราเร็วและความยาวคลื่นเปลี่ยน','waves','ม.5','vpl02',['Refraction']),
 ('vlab:vpl02:lab-34', V2+'34. wave-diffraction-interference.html','34','การเลี้ยวเบนและแทรกสอด','ช่องเดี่ยว ช่องคู่ แถบสว่าง-มืด','waves','ม.5','vpl02',['Diffraction','Interference']),
 ('vlab:vpl02:lab-37', V2+'37. standing-waves.html','37','คลื่นนิ่งบนเส้นเชือก','บัพ ปฏิบัพ ฮาร์มอนิก','waves','ม.5','vpl02',['Standing wave']),
 ('vlab:vpl02:lab-38', V2+'38. wave-speed-on-string.html','38','ความเร็วคลื่นในเส้นเชือก','v = √(T/μ) ปรับความตึงและมวลต่อความยาว','waves','ม.5','vpl02',['Waves']),
 ('vlab:vpl02:lab-39', V2+'39. phase-circle-wave.html','39','เฟส · วงกลมอ้างอิง · y-x','Virtual Lab 3-in-1 · กราฟ y-t · วิเคราะห์ Δφ','waves','ม.5','vpl02',['เฟส']),
 ('vlab:vpl02:lab-40', V2+'40. pulse-superposition.html','40','การซ้อนทับของคลื่นดล','หลักการซ้อนทับ เสริม/หักล้าง','waves','ม.5','vpl02',['Superposition']),
 ('vlab:vpl02:lab-41', V2+'41. wave-interference-two-source.html','41','การแทรกสอดของคลื่นผิวน้ำ','แหล่งกำเนิดอาพันธ์ 2 แหล่ง แนวบัพ-ปฏิบัพ','waves','ม.5','vpl02',['Interference']),
 ('vlab:vpl02:lab-44', V2+'44. standing-waves-air-column.html','44','คลื่นนิ่งของเสียงในหลอดอากาศ','หลอดปลายปิด/เปิด หาความถี่กำทอนและอัตราเร็วเสียง','sound','ม.5','vpl02',['Sound','Resonance']),
 ('vlab:vpl02:lab-32b',V2+'32B. light-reflection.html','32B','การสะท้อนของแสง','กฎการสะท้อน กระจกเงาราบ','light','ม.5','vpl02',['Optics']),
 ('vlab:vpl02:lab-33b',V2+'33B. light-refraction-glass.html','33B','การหักเหของแสง (อากาศ→แก้ว)','กฎของสเนลล์ ดรรชนีหักเห','light','ม.5','vpl02',['Optics']),
 ('vlab:vpl02:lab-35', V2+'35. images-converging-lenses.html','35','ภาพจากเลนส์นูน (3D)','ม้านั่งเชิงแสง 3 มิติ · หาโฟกัสด้วยแสงขนาน · ภาพจริง/เสมือน · วัดค่าเอง · สมการเลนส์บาง','light','ม.5','vpl02',['Lens','3D']),
 ('vlab:vpl02:lab-36', V2+'36. images-diverging-lenses.html','36','ภาพจากเลนส์เว้า & กล้องกาลิเลโอ','ภาพเสมือน กล้องโทรทรรศน์แบบกาลิเลโอ','light','ม.5','vpl02',['Lens']),
 ('vlab:vpl02:lab-46', V2+'46. images-concave-mirror.html','46','ภาพจากกระจกเว้า (3D)','ม้านั่งเชิงแสง 3 มิติ · หาโฟกัสด้วยแสงขนาน · ภาพจริง/เสมือน · วัดค่าเอง · f = R/2','light','ม.5','vpl02',['Mirror','3D']),
 ('vlab:vpl02:lab-43', V2+'43. big-bang-theory.html','43','ทฤษฎีบิกแบง (Big Bang Theory)','Hubble · BBN · CMB · Build Lab','astro','ม.6','vpl02',['Cosmology']),
 ('vlab:vpl02:lab-45', V2+'45. expanding-universe-balloon.html','45','แบบจำลองการขยายตัวของเอกภพ','ลูกโป่ง = เอกภพ · วัดระยะ-ความเร็ว · กราฟ Hubble v = H·d (กิจกรรม 1.2)','astro','ม.6','vpl02',['Cosmology','Hubble']),
]
SERIES={'vpl01':('VPL 01','Virtual Physics Lab 01'),'vpl02':('VPL 02','Virtual Physics Lab 02'),'vpl03':('VPL 03','Virtual Physics Lab 03 · ปฏิบัติการ ม.')}
